import { defineStore } from 'pinia'
import { ref } from 'vue'

export const useUserStore = defineStore('userStore', () => {
	const users = ref([
		{
			id: 1,
			name: 'Joe Peach',
			email: 'Joe.Peach@example.com',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-11-20',
		},
		{
			id: 2,
			name: 'Pierre Dunn',
			email: 'Pierre.Dunn@example.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-11-18',
		},
		{
			id: 3,
			name: 'Jack Swallows',
			email: 'Jack.Swallows@example.com',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-11-22',
		},
		{
			id: 4,
			name: 'Max Payne',
			email: 'max.payne@bulletmail.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-11-19',
		},
		{
			id: 5,
			name: 'Marcus Phoenix',
			email: 'marcus.phoenix@gearsofmail.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-11-23',
		},
		{
			id: 6,
			name: 'Naruto Uzumaki',
			email: 'naruto@ramenlove.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-11-21',
		},
		{
			id: 7,
			name: 'Sol Goodman',
			email: 'sol.goodman@bettercallmail.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-11-17',
		},
		{
			id: 8,
			name: 'Donald Trump',
			email: 'donald.trump@buildthatmail.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-11-16',
		},
		{
			id: 9,
			name: 'The Devil',
			email: 'lucifer@hellmail.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-11-15',
		},
		{
			id: 10,
			name: 'Joker',
			email: 'joker@whysoemail.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-11-14',
		},
		{
			id: 11,
			name: 'Hideo "Genius" Kojima',
			email: 'hideo.kojima@strandmail.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-11-13',
		},
		{
			id: 12,
			name: 'Jotaro Kujo',
			email: 'jotaro.kujo@starplatinum.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-11-12',
		},
		{
			id: 13,
			name: 'Vitaly "Arthas" Tsal',
			email: 'uncle.bogdan@slapower.net',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-11-11',
		},
		{
			id: 14,
			name: 'Justin Freeman',
			email: 'xwilliams@munoz-lane.com',
			role: 'Admin',
			status: 'Inactive',
			createdAt: '2024-11-01',
		},
		{
			id: 15,
			name: 'Jeffrey Williams',
			email: 'charlesmiller@powers.com',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-12-19',
		},
		{
			id: 16,
			name: 'Natasha Nichols',
			email: 'andersonvanessa@yahoo.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-04-29',
		},
		{
			id: 17,
			name: 'Thomas Morse',
			email: 'manngregg@brooks.biz',
			role: 'Admin',
			status: 'Inactive',
			createdAt: '2024-10-13',
		},
		{
			id: 18,
			name: 'Christina Reyes',
			email: 'pdavis@jackson.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-01-10',
		},
		{
			id: 19,
			name: 'Martha Baker',
			email: 'teresamendoza@haley-young.info',
			role: 'Moderator',
			status: 'Inactive',
			createdAt: '2024-01-01',
		},
		{
			id: 20,
			name: 'Javier Gates',
			email: 'steven78@yahoo.com',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-08-23',
		},
		{
			id: 21,
			name: 'Brandon Haynes',
			email: 'xwhite@gmail.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-03-14',
		},
		{
			id: 22,
			name: 'Paul Green',
			email: 'meganstrickland@espinoza-mack.net',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-04-19',
		},
		{
			id: 23,
			name: 'Eugene Johnson',
			email: 'melissa48@yahoo.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-08-19',
		},
		{
			id: 24,
			name: 'Amber Morrow',
			email: 'jacobmccarthy@holmes-acevedo.org',
			role: 'User',
			status: 'Active',
			createdAt: '2024-02-16',
		},
		{
			id: 25,
			name: 'Joseph Foley',
			email: 'bfoster@gmail.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-10-12',
		},
		{
			id: 26,
			name: 'Lisa Pham',
			email: 'bryan46@dalton.com',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-10-19',
		},
		{
			id: 27,
			name: 'Stephen Padilla',
			email: 'alyssawalton@gmail.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-11-16',
		},
		{
			id: 28,
			name: 'Wendy Holt',
			email: 'reneemullins@yahoo.com',
			role: 'Moderator',
			status: 'Inactive',
			createdAt: '2024-11-29',
		},
		{
			id: 29,
			name: 'Bryan Singh',
			email: 'isaacmoore@barker.com',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-03-06',
		},
		{
			id: 30,
			name: 'Amanda Hubbard',
			email: 'michelle28@love.com',
			role: 'Moderator',
			status: 'Inactive',
			createdAt: '2024-09-16',
		},
		{
			id: 31,
			name: 'Rebecca Prince',
			email: 'chavezronald@weber.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-04-21',
		},
		{
			id: 32,
			name: 'Stacey Porter',
			email: 'briansmith@gmail.com',
			role: 'Admin',
			status: 'Inactive',
			createdAt: '2024-01-25',
		},
		{
			id: 33,
			name: 'Elizabeth Garrett',
			email: 'nicole42@yahoo.com',
			role: 'Moderator',
			status: 'Inactive',
			createdAt: '2024-02-15',
		},
		{
			id: 34,
			name: 'Stephen Phillips DVM',
			email: 'brandiadams@gmail.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-11-14',
		},
		{
			id: 35,
			name: 'Jeremy Dennis',
			email: 'zoesimpson@gmail.com',
			role: 'Moderator',
			status: 'Inactive',
			createdAt: '2024-10-03',
		},
		{
			id: 36,
			name: 'Jordan Nichols',
			email: 'christineburns@johnston-stevens.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-11-18',
		},
		{
			id: 37,
			name: 'Michael Patterson',
			email: 'morrisjames@yahoo.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-10-03',
		},
		{
			id: 38,
			name: 'Amy Clarke',
			email: 'julia80@johnson.info',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-01-20',
		},
		{
			id: 39,
			name: 'Tina Coleman',
			email: 'brownrenee@humphrey.biz',
			role: 'Admin',
			status: 'Inactive',
			createdAt: '2024-07-28',
		},
		{
			id: 40,
			name: 'Jacob Clark',
			email: 'antonioferrell@smith.net',
			role: 'User',
			status: 'Active',
			createdAt: '2024-01-21',
		},
		{
			id: 41,
			name: 'Derrick Peterson',
			email: 'tuckerkelly@gmail.com',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-05-16',
		},
		{
			id: 42,
			name: 'Michael Baker',
			email: 'smitherica@yahoo.com',
			role: 'Moderator',
			status: 'Inactive',
			createdAt: '2024-09-09',
		},
		{
			id: 43,
			name: 'Stephen Cline',
			email: 'stewartmichelle@hotmail.com',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-08-18',
		},
		{
			id: 44,
			name: 'Susan Chandler',
			email: 'james23@aguirre.info',
			role: 'User',
			status: 'Active',
			createdAt: '2024-05-10',
		},
		{
			id: 45,
			name: 'Mary Payne',
			email: 'jameschung@miller.info',
			role: 'Admin',
			status: 'Inactive',
			createdAt: '2024-05-30',
		},
		{
			id: 46,
			name: 'Donna Williams',
			email: 'bairddiana@fleming.com',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-04-13',
		},
		{
			id: 47,
			name: 'Patricia Beasley',
			email: 'ricky29@butler.com',
			role: 'Admin',
			status: 'Inactive',
			createdAt: '2024-09-05',
		},
		{
			id: 48,
			name: 'Brenda Jones',
			email: 'crystal24@peterson.org',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-05-10',
		},
		{
			id: 49,
			name: 'Tiffany Mitchell',
			email: 'anthony00@byrd.net',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-08-26',
		},
		{
			id: 50,
			name: 'Matthew Berry',
			email: 'qrogers@gmail.com',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-12-02',
		},
		{
			id: 51,
			name: 'Karen Sutton',
			email: 'danielcrane@yahoo.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-08-19',
		},
		{
			id: 52,
			name: 'Brandi Perez',
			email: 'tasha38@hotmail.com',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-05-18',
		},
		{
			id: 53,
			name: 'Daniel Jones',
			email: 'mark65@gmail.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-11-25',
		},
		{
			id: 54,
			name: 'Emily Howell',
			email: 'leelisa@yahoo.com',
			role: 'Moderator',
			status: 'Inactive',
			createdAt: '2024-09-19',
		},
		{
			id: 55,
			name: 'James Cooper',
			email: 'zphillips@alexander.biz',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-08-11',
		},
		{
			id: 56,
			name: 'Christopher Miller',
			email: 'martinmcmillan@gmail.com',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-01-31',
		},
		{
			id: 57,
			name: 'Elizabeth Obrien',
			email: 'joshua87@yahoo.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-02-27',
		},
		{
			id: 58,
			name: 'Eric Sanford',
			email: 'raymond13@kirk.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-08-11',
		},
		{
			id: 59,
			name: 'Kayla Ortiz',
			email: 'oscott@myers.com',
			role: 'Admin',
			status: 'Inactive',
			createdAt: '2024-08-19',
		},
		{
			id: 60,
			name: 'Maureen Anderson',
			email: 'farrelllinda@williams-daniels.com',
			role: 'Admin',
			status: 'Inactive',
			createdAt: '2024-12-07',
		},
		{
			id: 61,
			name: 'Andrew Braun',
			email: 'jamesrobert@gmail.com',
			role: 'Admin',
			status: 'Inactive',
			createdAt: '2023-12-26',
		},
		{
			id: 62,
			name: 'Edwin Miles',
			email: 'meyerkimberly@yahoo.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-02-27',
		},
		{
			id: 63,
			name: 'Brandon Jones',
			email: 'barkerstephen@gmail.com',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-09-18',
		},
		{
			id: 64,
			name: 'Christopher Atkins',
			email: 'edwardslaurie@hotmail.com',
			role: 'Moderator',
			status: 'Inactive',
			createdAt: '2024-05-03',
		},
		{
			id: 65,
			name: 'Jordan Johnson',
			email: 'maldonadosteven@yahoo.com',
			role: 'Admin',
			status: 'Inactive',
			createdAt: '2024-01-04',
		},
		{
			id: 66,
			name: 'Ryan Baker',
			email: 'rebeccajoyce@may.org',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-05-07',
		},
		{
			id: 67,
			name: 'David Wagner',
			email: 'pmcdowell@yahoo.com',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-11-12',
		},
		{
			id: 68,
			name: 'Dominic Bond',
			email: 'carol88@cooper-farrell.info',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-10-31',
		},
		{
			id: 69,
			name: 'Julia Russell',
			email: 'honicole@griffin-graham.net',
			role: 'User',
			status: 'Active',
			createdAt: '2024-12-15',
		},
		{
			id: 70,
			name: 'Pam Garrett',
			email: 'shelly92@gmail.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-08-10',
		},
		{
			id: 71,
			name: 'Dr. Michelle Taylor PhD',
			email: 'laurenmcdonald@daniels.com',
			role: 'Moderator',
			status: 'Inactive',
			createdAt: '2024-11-16',
		},
		{
			id: 72,
			name: 'Victoria Roberts',
			email: 'ideleon@graves-dalton.com',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-12-09',
		},
		{
			id: 73,
			name: 'Lance Gregory',
			email: 'wspears@williams.com',
			role: 'Moderator',
			status: 'Inactive',
			createdAt: '2024-04-06',
		},
		{
			id: 74,
			name: 'Michael Wallace',
			email: 'lori89@young.org',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-01-11',
		},
		{
			id: 75,
			name: 'Gary Potts',
			email: 'troy76@hotmail.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-08-21',
		},
		{
			id: 76,
			name: 'Angela Anderson',
			email: 'gonzalezpeggy@miller-evans.com',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-06-07',
		},
		{
			id: 77,
			name: 'Alyssa Richardson',
			email: 'lchapman@george-duke.net',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-05-03',
		},
		{
			id: 78,
			name: 'Zachary Rose',
			email: 'fcunningham@morales.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-10-19',
		},
		{
			id: 79,
			name: 'Megan Andrews',
			email: 'huynhjody@davis.com',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-07-11',
		},
		{
			id: 80,
			name: 'Jacob Hansen',
			email: 'lisahaynes@hotmail.com',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-06-02',
		},
		{
			id: 81,
			name: 'Megan Crane',
			email: 'wendymoore@jones.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-09-30',
		},
		{
			id: 82,
			name: 'Benjamin Williams',
			email: 'morganharris@bennett-jones.com',
			role: 'Moderator',
			status: 'Inactive',
			createdAt: '2024-10-04',
		},
		{
			id: 83,
			name: 'Rhonda Kelley',
			email: 'dhayes@terry.net',
			role: 'User',
			status: 'Active',
			createdAt: '2024-09-25',
		},
		{
			id: 84,
			name: 'Robert Blackburn',
			email: 'robertgamble@velazquez-jones.com',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-05-08',
		},
		{
			id: 85,
			name: 'Maureen Carroll',
			email: 'ngreer@lopez-white.org',
			role: 'Moderator',
			status: 'Inactive',
			createdAt: '2024-07-07',
		},
		{
			id: 86,
			name: 'Robert Harris',
			email: 'karen60@yahoo.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-04-29',
		},
		{
			id: 87,
			name: 'Charles Lawrence',
			email: 'gabrielleshaw@martinez.com',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-03-01',
		},
		{
			id: 88,
			name: 'Rebecca Brown',
			email: 'wjohnson@hernandez.com',
			role: 'User',
			status: 'Active',
			createdAt: '2023-12-29',
		},
		{
			id: 89,
			name: 'Christopher Cook PhD',
			email: 'smithheather@yahoo.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-05-12',
		},
		{
			id: 90,
			name: 'Kim Bennett',
			email: 'jennifer51@wells.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-11-28',
		},
		{
			id: 91,
			name: 'Mikayla Scott',
			email: 'bbrown@yahoo.com',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-11-20',
		},
		{
			id: 92,
			name: 'Bruce Bruce',
			email: 'schmidtalison@yahoo.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-07-14',
		},
		{
			id: 93,
			name: 'Mary Richardson',
			email: 'kmurphy@vega.com',
			role: 'Moderator',
			status: 'Inactive',
			createdAt: '2024-08-26',
		},
		{
			id: 94,
			name: 'Stephanie Webster',
			email: 'kaylee29@yahoo.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-05-21',
		},
		{
			id: 95,
			name: 'Tony Molina',
			email: 'andersonlaura@davidson.biz',
			role: 'User',
			status: 'Active',
			createdAt: '2024-01-27',
		},
		{
			id: 96,
			name: 'Nicholas Parks',
			email: 'gregorywright@hotmail.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-06-26',
		},
		{
			id: 97,
			name: 'Kristin Patel',
			email: 'kaitlyn18@yahoo.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-07-07',
		},
		{
			id: 98,
			name: 'Beverly Miller',
			email: 'brownrhonda@yahoo.com',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-05-19',
		},
		{
			id: 99,
			name: 'Kayla Garza',
			email: 'douglasmegan@yahoo.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-12-19',
		},
		{
			id: 100,
			name: 'Angel Thomas',
			email: 'travisnewman@yahoo.com',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-02-09',
		},
		{
			id: 101,
			name: 'Leslie Jones',
			email: 'lindsey48@saunders.org',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-04-26',
		},
		{
			id: 102,
			name: 'Jonathan Martinez',
			email: 'zclark@hunter-logan.com',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-09-17',
		},
		{
			id: 103,
			name: 'Amber Carroll',
			email: 'steven57@gmail.com',
			role: 'Admin',
			status: 'Inactive',
			createdAt: '2024-05-18',
		},
		{
			id: 104,
			name: 'Barbara Houston',
			email: 'mariamiller@wright-lee.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-07-04',
		},
		{
			id: 105,
			name: 'John Flores',
			email: 'simmonsjennifer@perkins-gray.com',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-04-12',
		},
		{
			id: 106,
			name: 'Eugene Forbes',
			email: 'judith22@sweeney.com',
			role: 'Moderator',
			status: 'Inactive',
			createdAt: '2024-07-02',
		},
		{
			id: 107,
			name: 'Abigail Nguyen',
			email: 'reyespamela@petersen.biz',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-06-30',
		},
		{
			id: 108,
			name: 'Michael Boone',
			email: 'jessica78@lopez-baker.com',
			role: 'Admin',
			status: 'Active',
			createdAt: '2024-12-10',
		},
		{
			id: 109,
			name: 'Sharon Griffith',
			email: 'billyevans@wright-ramsey.com',
			role: 'Admin',
			status: 'Inactive',
			createdAt: '2024-02-02',
		},
		{
			id: 110,
			name: 'Sandra Cruz',
			email: 'michael73@hotmail.com',
			role: 'Moderator',
			status: 'Active',
			createdAt: '2024-11-23',
		},
		{
			id: 111,
			name: 'Matthew Mclean',
			email: 'hudsonjessica@yahoo.com',
			role: 'Admin',
			status: 'Inactive',
			createdAt: '2024-07-29',
		},
		{
			id: 112,
			name: 'Mr. Eugene Smith',
			email: 'robert82@hotmail.com',
			role: 'User',
			status: 'Active',
			createdAt: '2024-07-30',
		},
		{
			id: 113,
			name: 'Marie Davis',
			email: 'kennedyjulia@scott.com',
			role: 'User',
			status: 'Inactive',
			createdAt: '2024-03-13',
		},
	])

	// Удаление пользователя
	const deleteUser = (id: number) => {
		users.value = users.value.filter(user => user.id !== id)
	}

	return { users, deleteUser }
})
